### ISSUE TITLE
dev folder outside of ui folder?

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit-ui#17]
So I'm wondering if it's not better to have the `dev` folder outside of the `ui` folder.

I think there's a little bit more clarity with this structure:
```
/app-extenions
/ui
/dev
```
since each folder has its own package.json file.

Or is there a special reason the `dev` folder is placed _inside_ the `ui` folder?

**Comment by mesqueeb** [comment]
I've tried to move the `dev` folder outside of `ui` so I have the more clear folder structure I explained above. (and I renamed `/dev` then to `/demo`)
I made sure I updated all relative/absolute paths that were used in the demo.

However, I cannot run `quasar dev` or `quasar build` in the new `/demo` folder because it doesn't have the dependency called `quasar` and that throws an error on this line:

<img width="649" alt="Screenshot 2019-10-18 11 58 38" src="https://user-images.githubusercontent.com/3253920/67062686-05bedf80-f19f-11e9-8173-1da75dc19f59.png">

The error is:

<img width="814" alt="image" src="https://user-images.githubusercontent.com/3253920/67062708-1a9b7300-f19f-11e9-99a1-c23865060e89.png">

At this location: `@quasar/app/lib/helpers/banner.js:5`

**Comment by mesqueeb** [comment]
I created a PR that solves this issue:
https://github.com/quasarframework/quasar/pull/5333

**Comment by rstoenescu** [comment]
Hi,

This is not an issue. The dev folder refers just to the UI package, so it makes sense to be there.
Also, this template is not to be taken as a rigid structure. Based on specific requirements, it can be tweaked to everyone's desires.
