### ISSUE TITLE
/dev folder doesn't have quasar.variables.sass

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit-ui#21]

**Comment by mesqueeb** [comment]
👆
opened a PR that solves it

**Comment by rstoenescu** [comment]
Hi,

Why would you need this? The dev app is not important. It's just a way to test to test the UI component/directive..

**Comment by mesqueeb** [comment]
@rstoenescu 
The dev folder is actually very good to use as base for the demo of the ui component.

In my case, for my next extension, I made a "page" for each of the features of my ui component, to test, but then I just added some explananion to this page so it's usable as demo. 😉
