### ISSUE TITLE
Cannot execute formatDate util

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit-ui#3]
Hi,
I know it says:
> Do not use, do not ask...

However, the kit is so good it got me so excited I couldn't help myself to start writing my long due app extension with this kit!

### formatDate util

I try to execute the following inside a vue file component from the `ui/src` folder (which I load into the `dev` quasar project)

```js
import { date } from 'quasar'
const { formatDate } = date
formatDate(new Date(), 'YYYY/MM/DD')
```

but it gives an error:

<img width="370" alt="image" src="https://user-images.githubusercontent.com/3253920/65580501-bed13600-dfb4-11e9-9873-1db8f5106f7a.png">

I think that perhaps it's not properly retrieving all the required dependencies when importing `date`.

**Comment by rstoenescu** [comment]
Hi @mesqueeb 

Can't reproduce. Can you create a reproduction repo pls?

**Comment by mesqueeb** [comment]
@rstoenescu thanks for your comment!

I've uploaded the app extension here. Please use the `broken-parts` branch:

https://github.com/mesqueeb/quasar-app-extension-easy-forms/tree/broken-parts


See here the two errors I'm having:

## Broken date utils

<img width="959" alt="image" src="https://user-images.githubusercontent.com/3253920/65653595-d52ccf80-e050-11e9-9df0-d35181775b55.png">

## Broken Platform at QSelect import

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/3253920/65653638-fdb4c980-e050-11e9-8194-8b2c1d7ab683.png">

**Comment by rstoenescu** [comment]
Take a look at https://github.com/quasarframework/quasar-starter-kit-ui/commit/000c42c0081af77b8fb131e3e704ce0a2795c57e

Do the same in your app, then delete ui/dev/node_modules and ui/dev/yarn.lock (or package-lock.json) and yarn/npm install again in ui/dev.

**Comment by rstoenescu** [comment]
And thanks for reporting!
