### ISSUE TITLE
How to use peer dependency in UI component?

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit-ui#38]
I have 2 Quasar UI components: `easy-tables` and `easy-forms`.
Easy Tables uses Easy Forms as dependency as well.

I want to make sure that these always stay the same version:
- Easy Forms as dependency of Easy Tables
- Easy Forms installed directly

Therefore I had [listed Easy Forms as a peer dependency of Easy Tables](https://github.com/mesqueeb/quasar-ui-easy-tables/blob/master/ui/package.json#L27).

However, it seems that the UI build scripts & bundlers still include the full code for Easy Forms, therefore creating the situation where Easy Forms can be a higher version when installed directly than the one installed as dependency of Easy Tables.
(this actually happened to me)

How can I make sure that the build script of my UI components won't include peer Dependencies in its bundles?

**Comment by rstoenescu** [comment]
Hi,

Check the js build script and look for globals/external. Take “quasar” package as an example.

**Comment by mesqueeb** [comment]
@rstoenescu thanks for the quick answer!
It worked like a charm 💜
