### ISSUE TITLE
Do not minify by default

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit-ui#41]
What is the reason that the built files in `ui/dist` are minified by default?

I believe that the built files `index.esm.js` and `index.common.js` are always imported into quasar projects via npm, and thus included in a vue or quasar project which minifies the end result with webpack or rollup.

Therefore I believe it's better to have them not minified by default.

This is especially true if you want to step through code of UI components when importing them in another project. Stepping through minified JS is near impossible.

**Comment by rstoenescu** [comment]
Hi,

This can easily be customized in the build file of the starter kit. You can even add an uniminified version along with the minified one.
But the reason to minimize by default is that: 1. saves bandwidth when installing npm package; 2. quasar/app takes a whole lot let to minimize an already minimized file :)
