### ISSUE TITLE
How can i add axios default header in Quasar ^2.0.0

### ISSUE THREAD

**Issue by shahriar350** [quasarframework/quasar-starter-kit-ui#51]
![image](https://user-images.githubusercontent.com/44544213/107887654-c985c580-6f31-11eb-8986-8194e3febe54.png)
![image](https://user-images.githubusercontent.com/44544213/107887829-0dc59580-6f33-11eb-8191-83fc5a030f61.png)

in Quasar.config
plugins: [
        'Cookies'
      ]
Now how can I add this default header in SSR mode?

**Comment by mesqueeb** [comment]
I think `import { Cookies } from 'quasar'`

**Comment by shahriar350** [comment]
> I think
> 
> ```js
> import { Cookies } from 'quasar'
> 
> Cookies.get(...
> ```

![image](https://user-images.githubusercontent.com/44544213/107900816-59486580-6f6c-11eb-8f79-b490fa25db0c.png)
![image](https://user-images.githubusercontent.com/44544213/107900846-71b88000-6f6c-11eb-9f7a-33d9b5a50a32.png)

**Comment by mesqueeb** [comment]
in server side rendering you cannot access the user's browser's cookies.

Think about it... how can the server know what cookies live in the browser?

The whole idea about SSR is that the server tries to create the UI _before_ that UI is sent to the browser.

**Comment by shahriar350** [comment]
> in server side rendering you cannot access the user's browser's cookies.
> 
> Think about it... how can the server know what cookies live in the browser?
> 
> The whole idea about SSR is that the server tries to create the UI _before_ that UI is sent to the browser.

So now, what is the solution because I need to sent csrf token which in my cookie. I use Django as backend. Without csrftoken, Django rejected the connection.

**Comment by shahriar350** [comment]
> in server side rendering you cannot access the user's browser's cookies.
> 
> Think about it... how can the server know what cookies live in the browser?
> 
> The whole idea about SSR is that the server tries to create the UI _before_ that UI is sent to the browser.

Now it is ok. i use js-cookie package and proxy.

**Comment by rstoenescu** [comment]
The cookies are sent through HTTP headers. So Cookies plugin can handle cookies server-side too.
https://quasar.dev/quasar-plugins/cookies#Notes-on-SSR

Put that in the default exporting function (where you have access to the ssrContext).
