### ISSUE TITLE
Dialog.create is not a function

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-starter-kit-ui#9]
I'm havinig a similar problem then last time (#3 )
but this time with `Dialog`.

I do
```
import { Dialog } from 'quasar'
```
but I get these errors:

<img width="547" alt="image" src="https://user-images.githubusercontent.com/3253920/65832367-7fc91a80-e2fd-11e9-9838-ea8115e66b85.png">
<img width="545" alt="image" src="https://user-images.githubusercontent.com/3253920/65832368-83f53800-e2fd-11e9-96c7-002d4c2eb282.png">

**Comment by rstoenescu** [comment]
Hi,

Have you specified it in dev's quasar.conf.js? :)

**Comment by mesqueeb** [comment]
@rstoenescu No, I was trying to use it in the actual app-extension, so without requiring the user to add it to their project as well.

Would I still need to add `Dialog` to `/ui/dev/quasar.conf.js` even though I only use it in `/ui/src` ?
